name: Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize

jobs:
  backend_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: '12.x'
      - name: "npm install"
        run: |
          npm install
      - name: "setup env" 
        run: |
          touch .env
          echo URL=${{secrets.URL}} >> .env
          echo TESTURL=${{secrets.TEST_URL}} >> .env
          echo PORT=3001 >> .env
          echo SECRET=${{secrets.SECRET}} >> .env
      - name: lint
        run: |
          npm run lint
      - name: print
        run: |
          cat .env
      - name: test
        run: |
          npm test
      
  frontend_pipeline:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: '12.x'
      - name: "npm install"
        run: |
          npm install
      - name: lint
        run: |
          npm run lint
      - name: build
        run: |
          npm run build
      - name: test
        run: |
          npm test