name: Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize

jobs:
  backend_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: '12.x'
      - name: "npm install"
        run: |
          npm install
      - name: "setup env" 
        run: |
          touch .env
          echo "TESTURL=${{secrets.TEST_URL}}" >> .env
          echo "PORT=3001" >> .env
          echo "SECRET=${{secrets.SECRET}}" >> .env
      - name: lint
        run: |
          npm run lint
      - name: test
        run: |
          npm test
      
  frontend_pipeline:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: '12.x'
      - name: "npm install"
        run: |
          npm install
      - name: lint
        run: |
          npm run lint
      - name: build
        run: |
          npm run build
      - name: save frontend build
        uses: actions/upload-artifact@v2
        with: 
          name: frontend-build
          path: build
      - name: test
        run: |
          npm test
  deploy:
    runs-on: ubuntu-20.04
    needs: 
      - backend_pipeline
      - frontend_pipeline
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: frontend-build
      - name: deploy
        if: github.event_name == 'push'
        uses: akhileshns/heroku-deploy@v3.8.9
        with: 
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: mikon-blogit 
          heroku_email: "mikko.m.pirhonen@tuni.fi"
          healthcheck: "https://mikon-blogit.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
  version:
    runs-on: ubuntu-20.04
    needs: deploy
    if: |
      github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - uses: anothrNick/github-tag-action@1.34.0 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch 
